### ISSUE TITLE
Compatibility for Power BI Report Server

### ISSUE THREAD

**Issue by nessan77** [bhavesh-jadav/Advance-Card#24]
Advance card works fine in power bi desktop and cloud versión, but in report server the card isn't showing correctly, it's shown a shield with a cross inside.

**Comment by Drunprofits** [comment]
From late last week, Advance Card no longer displays date correctly: month is now shown as MM : this affects all the reports I have published back to mid October . I used Advance Card as a dated title on every page of hundreds of reports : these are all now showing months as MM only
can you please fix or revert to the version that was working fine!!!!!!

I now have to stop using Advance Card as each daily report will have for example 28 MM 2018 instead of 28 November 2018
example attached

help and revolution hugely appreciated as I may now have to rework hundreds of pages to manually remove Advance Card

![2018-11-27 10_33_21-uk markets mon 26nov 2018 - power bi desktop](https://user-images.githubusercontent.com/45169125/49141092-bb661300-f2ed-11e8-9f46-111ea0c52d3f.jpg)

**Comment by Drunprofits** [comment]
Hi

I am using last refresh to date the reports as I run them daily and update with new data

 

I tried the attached having removed the old Advance Card version

 

The attached still returns the MM in the month field: if I use the MSFT Card it returns the Month correctly

 

I have attached a screen grab of both on the same field using the same Refresh Query: Advance Card is on the Left showing MM

 

Thanks for getting abck so quick

 

D

**Comment by Drunprofits** [comment]
For completion here is  a copy of the same file on report server showing MM for Advance Card and the correct format for regular Card

**Comment by nessan77** [comment]
Hi @bhavesh-jadav 
I exchanged the card for the attached one, but the same icon still appears

**Comment by bhavesh-jadav** [comment]
@Drunprofits  see https://github.com/bhavesh-jadav/Advance-Card/issues/25#issuecomment-442402419

**Comment by fernandocalero** [comment]
I made a comment in the closed issue related to not showing the indicator in the card
